const data = {
    products: [
        {id: '1',
        name: 'DMM Dragon Cam 00 (Blue)',
        price: 220.99,
        image: 'https://www.skubank.com/imagestore/product/11981/33/160789/c63_11981_A73500A-dragon-cam-00.jpg',
        },
        {id: '2',
            name: 'DMM Dragon Cam 1 (Purple)',
            price: 235.79,
            image: 'https://www.skubank.com/imagestore/product/11981/33/160788/c63_11981_A7351A-dragon-cam1.jpg',
        },
        {id: '3',
            name: 'DMM Dragon Cam 3 (Red)',
            price: 250.29,
            image: 'https://www.skubank.com/imagestore/product/11981/33/160784/c63_11981_A7353A-dragon-cam-3.jpg',
        },
        {id: '4',
            name: 'Ekspres wspinaczkowy CT',
            price: 57.99,
            image: 'https://8a.pl/media/catalog/product/e/k/ekspres-wspinaczkowy-climbing-technology-aerial-pro-set-ny-12cm-blue-1653025693.jpg',
        },
        {id: '5',
            name: 'Ekspres wspinaczkowy CT Lime',
            price: 60.99,
            image: 'https://8a.pl/media/catalog/product/e/k/ekspres-wspinaczkowy-climbing-technology-lime-set-dy-12-cm-green-1652087922.jpg',
        },
        {id: '6',
            name: 'Lina Beal 9,1mm 50m',
            price: 500.99,
            image: 'https://8a.pl/media/catalog/product/l/i/lina-wspinaczkowa-beal-joker-9-1-mm-50m-unicore-dry-cover-orange-1653292780.jpg',
        },
        {id: '7',
            name: 'Lina Beal 8,5mm 50m',
            price: 512.99,
            image: 'https://8a.pl/media/catalog/product/l/i/lina-wspinaczkowa-beal-opera-8-5-mm-50m-unicore-dry-cover-green-1653291587.jpg',
        },
        {id: '8',
            name: 'Lina Beal 9,8mm 70m',
            price: 566.99,
            image: 'https://8a.pl/media/catalog/product/l/i/lina-wspinaczkowa-beal-karma-9-8-mm-70m-yellow-1653291831.jpg',
        },
        {id: '9',
            name: 'Zestaw ekspresów CT',
            price: 350.99,
            image: 'https://8a.pl/media/catalog/product/z/e/zestaw-ekspresow-climbing-technology-aerial-pro-set-dy-12-cm-x6-1650530888.jpg',
        },
        {id: '10',
            name: 'Woreczek na magnezję',
            price: 54.99,
            image: 'https://8a.pl/media/catalog/product/w/o/woreczek-na-magnezje-e9-aglio-c-wine-1652775810.jpg',
        },
        {id: '11',
            name: 'Czekan Grivel Ghost Evo',
            price: 386.99,
            image: 'https://8a.pl/media/catalog/product/c/z/czekan_grivel_ghost_evo_hammer_yellow_1631185462_d030.jpg',
        },
        {id: '12',
            name: 'Czekan Grivel G Zero',
            price: 236.99,
            image: 'https://8a.pl/media/catalog/product/c/z/czekan_grivel_g_zero_pink_1631282594_0c52.jpg',
        },
        {id: '13',
            name: 'Raki automatyczne Grivel G12',
            price: 590.39,
            image: 'https://8a.pl/media/catalog/product/r/a/raki_automatyczne_grivel_g12_cramp_o_matic_evo_1637653664_ecf7.jpg',
        },
        {id: '14',
            name: 'Sonda lawinowa BD Quickdraw',
            price: 359.99,
            image: 'https://8a.pl/media/catalog/product/s/o/sonda-lawinowa-black-diamond-quickdraw-pro-probe-320-green-1622551618.jpg',
        },
        {id: '15',
            name: 'Detektor lawinowy Ortovox',
            price: 1183.99,
            image: 'https://8a.pl/media/catalog/product/d/e/detektor-lawinowy-ortovox-diract-voice-blue-ocean-1645169493.jpg',
        },
        {id: '16',
            name: 'Śruba lodowa Petzl Laser 13cm',
            price: 189.99,
            image: 'https://8a.pl/media/catalog/product/s/r/sruba-lodowa-petzl-laser-13cm-1646042577.jpg',
        },
        {id: '17',
            name: 'Szabla śnieżna CT 50cm',
            price: 127.91,
            image: 'https://8a.pl/media/catalog/product/s/z/szabla_sniezna_climbing_technology_snow_anchor_50cm_1646210179_385d.jpg',
        },
        {id: '18',
            name: 'Lonża do czekana Grivel',
            price: 168.47,
            image: 'https://8a.pl/media/catalog/product/l/o/lonza_grivel_double_spring_screw_lock_1570447927_4c6c.jpg',
            details: 'Lonża do czekana Grivel Double Spring ma prostą konstrukcję. W pierwszej chwili sprawia wrażenie niepozornej,' +
                ' ale zapewnia szerokie możliwości użytkowe. Ten niewielki gadżet wiele zmieni. Model składa się z dwóch ramion ' +
                'taśm połączonych pętlą. Na końcu każdej z nich znalazł się karabinek z funkcjonalnym zamkiem. Taka budowa ' +
                'znacznie ułatwia użytkowanie czekanów w czasie wspinaczki lodowej. Taśma umożliwia bardzo proste zamocowanie' +
                ' do uprzęży, a elastyczność w znacznym stopniu poprawia komfort operowania sprzętem. Wpięcie czekanów nie ' +
                'będzie problematyczne, a zniweluje ryzyko przypadkowego zgubienia sprzętu. Dosięgnięcie do nich zarówno z prawej, ' +
                'jak i lewej strony nie sprawi trudności.'
        }

    ]
};
export default data;